modelname="LSTM"
usewandb=""
epoch="20"
warmupepoch="4"
blr="3e-1"
seed="5"
batchsize="32"
layerdecay="1" 
weightdecay="0.05"
droppath="0.1" 
datapercent="5"
offset=4
pos_embed_dim="12"
mask_type="no"
h="--same_normalizer --mask_type ${mask_type}"
htail="${mask_type}"
downstream="capacity"
log_dir="logs/capacity/${htail}/${modelname}/epoch${epoch}_blr${blr}_bsz${batchsize}_ld${layerdecay}_wd${weightdecay}_dp${droppath}_posembeddim${pos_embed_dim}/s${seed}"

mkdir -p $log_dir


brandnum="1"
CUDA_VISIBLE_DEVICES=`expr 0 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 0 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f0_b${brandnum} > ${log_dir}/f0_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 1 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 1 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f1_b${brandnum} > ${log_dir}/f1_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 2 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 2 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f2_b${brandnum} > ${log_dir}/f2_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 3 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 3 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f3_b${brandnum} > ${log_dir}/f3_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 3 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 4 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f4_b${brandnum} > ${log_dir}/f4_b${brandnum}.txt 2>&1 &

brandnum="2"
CUDA_VISIBLE_DEVICES=`expr 0 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 0 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f0_b${brandnum} > ${log_dir}/f0_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 0 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 1 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f1_b${brandnum} > ${log_dir}/f1_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 1 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 2 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f2_b${brandnum} > ${log_dir}/f2_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 1 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 3 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f3_b${brandnum} > ${log_dir}/f3_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 2 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 4 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f4_b${brandnum} > ${log_dir}/f4_b${brandnum}.txt 2>&1 &

brandnum="3"
CUDA_VISIBLE_DEVICES=`expr 0 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 0 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f0_b${brandnum} > ${log_dir}/f0_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 0 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 1 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f1_b${brandnum} > ${log_dir}/f1_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 1 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 2 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f2_b${brandnum} > ${log_dir}/f2_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 1 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 3 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f3_b${brandnum} > ${log_dir}/f3_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 2 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 4 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f4_b${brandnum} > ${log_dir}/f4_b${brandnum}.txt 2>&1 &

brandnum="4"
CUDA_VISIBLE_DEVICES=`expr 3 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 0 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f0_b${brandnum} > ${log_dir}/f0_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 3 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 1 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f1_b${brandnum} > ${log_dir}/f1_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 3 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 2 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f2_b${brandnum} > ${log_dir}/f2_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 3 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 3 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f3_b${brandnum} > ${log_dir}/f3_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 3 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 4 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f4_b${brandnum} > ${log_dir}/f4_b${brandnum}.txt 2>&1 &

brandnum="5"
CUDA_VISIBLE_DEVICES=`expr 1 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 0 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f0_b${brandnum} > ${log_dir}/f0_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 1 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 1 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f1_b${brandnum} > ${log_dir}/f1_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 1 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 2 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f2_b${brandnum} > ${log_dir}/f2_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 1 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 3 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f3_b${brandnum} > ${log_dir}/f3_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 1 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 4 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f4_b${brandnum} > ${log_dir}/f4_b${brandnum}.txt 2>&1 &

brandnum="6"
CUDA_VISIBLE_DEVICES=`expr 2 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 0 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f0_b${brandnum} > ${log_dir}/f0_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 2 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 1 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f1_b${brandnum} > ${log_dir}/f1_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 2 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 2 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f2_b${brandnum} > ${log_dir}/f2_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 2 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 3 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f3_b${brandnum} > ${log_dir}/f3_b${brandnum}.txt 2>&1 &
CUDA_VISIBLE_DEVICES=`expr 2 + ${offset}` nohup python -u main_finetune.py --batch_size ${batchsize} --model ${modelname} --epochs ${epoch} --warmup_epochs ${warmupepoch} --blr ${blr} --layer_decay ${layerdecay} --fold_num 4 --brand_num ${brandnum} --weight_decay ${weightdecay} --drop_path ${droppath} ${h} --pos_embed_dim ${pos_embed_dim} --seed ${seed} ${usewandb} --downstream ${downstream} --data_percent ${datapercent} --task batterybrandmileage --output_dir ${log_dir}/f4_b${brandnum} > ${log_dir}/f4_b${brandnum}.txt 2>&1 &
